#!/bin/bash
apm install atom-beautify 
apm install atom-bootstrap3
apm install atom-html-preview
apm install atom-react-preview
apm install atom-ungit
apm install auto-detect-indentation 
apm install autoclose-html
apm install babel-react-syntax
apm install emmet
apm install git-control
apm install git-plus
apm install highlight-selected
apm install indent-toggle-on-paste
apm install language-babel
apm install language-javascript-jsx
apm install language-jsx
apm install linter
apm install linter-eslint
apm install linter-js-standard
apm install monokai-seti 
apm install multi-cursor
apm install pigments 
apm install react
apm install react-snippets
apm install redux-snippets
apm install seti-ui 
apm install source-preview
apm install source-preview-babel
apm install toggle-quotes
apm install tree-view-git-branch
